language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "qPso1Gm/9XiZFBrkJvObMbzaoWo87rHgjqJdo7UK/OjfERdInPQ92+QZWnt37gP9S9fLswueAMgryJqUTlNrEC/fRbIgui/j+1tSM/rgLLMP+fdKzM+WPCiEVcI7wKFBK2zK+xi46ZPjYnFoe2Q0A5iD+Vfv7PNioxe2gAtE88KbclDO+5gPIJUqhi5vGGJdnqIvoEWwZutPSCoJNAwjJpiJRQR23sjXzGThFIi3yI/t88iPMENtmvdHEsZlqlB7hrACFfHdPc1iya9F7zMiuIV60/KW35fcILOUbjd+B8Yzvg2YShA8yMcGjlD8js5h5iSys8OGVCEjujqIK2LtgTcDAdpGXFqBzxUtf8us17JuyiJV+HjMqvJL1DJQyMmAbvFX2UsEmgc1Xyi4uNb2zKFtegkWgACyGwSILuvoTs0lexaOZOMRek7SXoaHWgtCYr3WJreP92IXpfaAwGgpjM0zF+JNTbO1li/BOlh/uWr5YQz9uc+PehGurQK1cA2w4KgAXixF9eN8pj1l34Tvq7dsVLFVIVtLeYwdk2evR4suYb/ZOt/W1oUQZNdt0/Y9ueIAlu/R1/HMmwflijkZw5Px77jaQ/kGQAGhlK/G7Z61aaJ6Zv++RFwALvs1Vh/dE4doeuUV7D+YG2H3eOx5drcMMVCgTKwwnFN6JbYimzg="
  - secure: "GiqjkGlbG8CKSLUd00r3PaqhSkqfXqZxlUEca9/lAomHOPkFlE94DQDtFxRchcWnXRHB5U2LLxf0W1gmP66+6CLHFaxLkH7L2AXv8095PmtLey3GpG86rSMtYexHWsC2xOVrn+vryOJ5h/Iqb0DOZln4eXCC8m2SQqkIkQrGwu4BVr7k1B0PhgCMC+ma/Nv0qFzzcreZSxEBZokDVz+O/rzGT/5P8Ll/fZRhHWMV7+YXcHJU9j8eylSGX4m0dyq9jJ6DxboHS6yt6RxPAsvY++BTAyrYe58QUY5AnvrnteXbkxv3sNIf0WEnWFzk88KoXCDkI0g33DZxRdbo/6hPRn8Id08uY9MA5JWPsiDxf4QVp3ETAvNAUq0VEv2J161KEou8+RHmVsJz+RydQJrgC8uUpGcwPOQZmFaeWd1+7qa4DhBKyHFdxVAtqRNZn8u/IRv4JetUjAj9Cvy2nrKo3NjYS3hmHRXF20/rx2+JEsVuZKQ9Z9lHwWHHEGTrl3MyyqhxkxKi9S8StoQ0ovd+NZ2sXin92d6VjOEB4/UMpfMnlROWZjTVIciyQckcTmJiqpxu1daFP+o6aikZCxkcPFBau2FSPG7nxej6gOVSP0TEhs6AY9WR2E1fOzpCQpA6uamTL1sNXKf2axClyTb0trOThUxb5PNUZKlkYNpnjXE="
deploy:
  provider: releases
  api_key: 
    secure: "XWehaw1CRmou7VlNhZ+pCX25DATh23S5yzuW9yiqHaumiY5x8lRqBqnQQahyFOoNknG/UzZOPXP2LUP71phZeaFigHUkOpH4kLmswpxtVzZSQJs+33fqwVIL3M04lGePSl+PuJ8/R/e4WfW6KBFcOkyQ3X0/MO/jIJKgTxyXd/8L0b74N7sOR2M+tdhreQcwAhYCaN3Uf1xXVrcdQWR7fzq7Li7znWWMBb6Cl3w3uhgPln7YXf2Go27KPmAEyvExnliU1CXYOIN59mk8RQG4c/cRzoECSSzzxElb+anuTwTRLtVp37gpnfXPBCgJItBdyJAPFFpv744ogMPeLcJ8gXkt/Saz6xAa6nPmfL87RkkOgV3Ydz7L5SElBOYdWByd4/7Fwu359ndnggbzMiPY5iW304Q9FRhtB3PBygOPoyNxjtgKsjiL11HvZQ1pl5hRryasCPAypD0/3gFGm6xk1PVQj+3usZ+SKCjfM5ZTY2GtJsHcAsR4da+iijMQUzmXBUg1Ki/tq+Q6Q3TFByjrYY80Ud4RWbdySmIrfdzoX+Yo5SyoF90sYtwVLpJgfTVY2KENcYtVOiXY6LBxXUvTyPb6LpaoaNjpKGk5EofIJxMup41zTYOVighLYLy/DSOOQfc/k9in8g+WKpYoeLK+GpGXV1/Eb68LJZOYW2wfAWs="
  file_glob: true
  file: 
    - "Plugin/target/NickNamer_v*.jar"
  skip_cleanup: true
  on:
    tags: true
